MODULE Precision
    INTEGER, PARAMETER :: dp = SELECTED_REAL_KIND(15, 307)
    INTEGER, PARAMETER :: qp = SELECTED_REAL_KIND(33, 4931)
    INTEGER, PARAMETER :: i4 = SELECTED_INT_KIND(4)
    INTEGER, PARAMETER :: i8 = SELECTED_INT_KIND(8)
    INTEGER, PARAMETER :: i10 = SELECTED_INT_KIND(10)
END MODULE Precision